from __future__ import annotations

import json
from pprint import pformat
from typing import Any, Dict

from rewarding.spec_schema import validate_reward_spec


def render_reward_code_from_spec(reward_spec: Dict[str, Any]) -> str:
    validated_spec = validate_reward_spec(reward_spec)
    spec_literal = pformat(validated_spec, sort_dicts=True, width=88)
    return _MODULE_TEMPLATE.replace("__REWARD_SPEC_LITERAL__", spec_literal)


_MODULE_TEMPLATE = """\
\"\"\"
Auto-generated dense reward module from a structured reward spec.

This file is generated by src/rewarding/spec_renderer.py.
Do not hand-edit this generated module unless you are debugging the renderer.
\"\"\"

from __future__ import annotations

SPEC = __REWARD_SPEC_LITERAL__

from rewarding.lbf_pbrs import build_lbf_pbrs_from_config


_PBRS_HELPER = build_lbf_pbrs_from_config(SPEC.get("pbrs"))


def compute_dense_reward(context):
    sparse_reward = context.sparse_reward
    raw_env = context.raw_env.unwrapped if hasattr(context.raw_env, "unwrapped") else context.raw_env
    dense_by_agent = _zero_like_list(sparse_reward)
    breakdown = {}

    players = list(getattr(raw_env, "players", []) or [])
    if not players:
        return _match_sparse_reward_shape(dense_by_agent, sparse_reward), breakdown

    target_assignments = _assign_target_foods(raw_env, players)
    previous_distances = _target_food_distances(context.obs_before, players, target_assignments)
    current_distances = _target_food_distances(context.obs_after, players, target_assignments)
    target_adjacency = _current_target_adjacency(players, target_assignments)
    coalition_ready = _coalition_readiness(players, raw_env, target_assignments)
    action_list = _actions_as_list(context.actions, len(players))
    sparse_list = _reward_as_list(context.sparse_reward, len(players))
    food_removed = _food_removed(context.state_before, context.state_after, raw_env)

    if _PBRS_HELPER is not None and context.lbf_state_before is not None and context.lbf_state_after is not None:
        _PBRS_HELPER.reset(context.lbf_state_before)
        pbrs_result = _PBRS_HELPER.compute_pbrs_reward(
            context.lbf_state_before,
            context.lbf_state_after,
            sparse_reward,
        )
        pbrs_shape = float(pbrs_result["reward_shape"])
        _add_scalar_to_dense(dense_by_agent, pbrs_shape)
        breakdown["pbrs"] = {
            "reward_shape": pbrs_shape,
            "phi_t": float(pbrs_result["phi_t"]),
            "phi_tp1": float(pbrs_result["phi_tp1"]),
            "variant": SPEC.get("pbrs", {}).get("variant", "original"),
            "beta": float(SPEC.get("pbrs", {}).get("beta", 0.0)),
            "wc": float(SPEC.get("pbrs", {}).get("wc", 0.0)),
            "wp": float(SPEC.get("pbrs", {}).get("wp", 0.0)),
            "gate_mode": SPEC.get("pbrs", {}).get("gate", {}).get("mode"),
            "gate_radius": SPEC.get("pbrs", {}).get("gate", {}).get("radius"),
            "closeness_mode": SPEC.get("pbrs", {}).get("closeness", {}).get("mode"),
        }

    for term in SPEC["terms"]:
        if not term.get("enabled", False):
            continue

        name = term["name"]
        weight = float(term["weight"])
        trigger_variant = term["trigger_variant"]
        constraints = term.get("constraints", {})
        contributions = _compute_term_contributions(
            name=name,
            trigger_variant=trigger_variant,
            weight=weight,
            constraints=constraints,
            players=players,
            action_list=action_list,
            sparse_list=sparse_list,
            previous_distances=previous_distances,
            current_distances=current_distances,
            target_assignments=target_assignments,
            target_adjacency=target_adjacency,
            coalition_ready=coalition_ready,
            raw_env=raw_env,
            food_removed=food_removed,
        )

        if not contributions:
            breakdown[name] = 0.0
            continue

        for idx, value in enumerate(contributions):
            dense_by_agent[idx] += value
        breakdown[name] = float(sum(contributions))

    dense_reward = _match_sparse_reward_shape(dense_by_agent, sparse_reward)
    return dense_reward, breakdown


def _compute_term_contributions(
    *,
    name,
    trigger_variant,
    weight,
    constraints,
    players,
    action_list,
    sparse_list,
    previous_distances,
    current_distances,
    target_assignments,
    target_adjacency,
    coalition_ready,
    raw_env,
    food_removed,
):
    if name == "approach_target_food":
        return _approach_target_food(
            weight=weight,
            trigger_variant=trigger_variant,
            constraints=constraints,
            previous_distances=previous_distances,
            current_distances=current_distances,
            target_assignments=target_assignments,
            target_adjacency=target_adjacency,
        )

    if name == "coordination_ready":
        return _coordination_ready(
            weight=weight,
            trigger_variant=trigger_variant,
            target_assignments=target_assignments,
            target_adjacency=target_adjacency,
            coalition_ready=coalition_ready,
        )

    if name == "load_attempt":
        return _load_attempt(
            weight=weight,
            trigger_variant=trigger_variant,
            players=players,
            action_list=action_list,
            target_adjacency=target_adjacency,
            coalition_ready=coalition_ready,
        )

    if name == "successful_load":
        return _successful_load(
            weight=weight,
            trigger_variant=trigger_variant,
            players=players,
            sparse_list=sparse_list,
            food_removed=food_removed,
        )

    if name == "failed_load_penalty":
        return _failed_load_penalty(
            weight=weight,
            trigger_variant=trigger_variant,
            players=players,
            action_list=action_list,
            sparse_list=sparse_list,
            target_adjacency=target_adjacency,
        )

    return [0.0 for _ in players]


def _approach_target_food(
    *,
    weight,
    trigger_variant,
    constraints,
    previous_distances,
    current_distances,
    target_assignments,
    target_adjacency,
):
    contributions = []
    same_target_counts = _target_agent_counts(target_assignments)
    for idx, current_distance in enumerate(current_distances):
        prev_distance = previous_distances[idx]
        target_food = target_assignments[idx]
        if prev_distance is None or current_distance is None or target_food is None:
            contributions.append(0.0)
            continue
        if current_distance >= prev_distance:
            contributions.append(0.0)
            continue
        if trigger_variant == "distance_decrease_not_adjacent" and target_adjacency[idx]:
            contributions.append(0.0)
            continue
        if constraints.get("only_when_not_adjacent") and target_adjacency[idx]:
            contributions.append(0.0)
            continue
        if trigger_variant == "distance_decrease_same_target" and same_target_counts.get(target_food, 0) < 2:
            contributions.append(0.0)
            continue
        contributions.append(float(weight))
    return contributions


def _coordination_ready(
    *,
    weight,
    trigger_variant,
    target_assignments,
    target_adjacency,
    coalition_ready,
):
    contributions = []
    same_target_counts = _target_agent_counts(target_assignments)
    for idx, target_food in enumerate(target_assignments):
        if target_food is None:
            contributions.append(0.0)
            continue

        if trigger_variant == "shared_food_adjacent":
            active = target_adjacency[idx] and same_target_counts.get(target_food, 0) >= 2
        elif trigger_variant == "coalition_level_sufficient":
            active = bool(coalition_ready[idx]["sufficient"])
        elif trigger_variant == "coalition_level_improves":
            active = bool(coalition_ready[idx]["improves"])
        else:
            active = False

        contributions.append(float(weight) if active else 0.0)
    return contributions


def _load_attempt(*, weight, trigger_variant, players, action_list, target_adjacency, coalition_ready):
    contributions = []
    for idx, _player in enumerate(players):
        did_load = action_list[idx] == 5
        if not did_load:
            contributions.append(0.0)
            continue
        if trigger_variant == "any_adjacent_load":
            active = target_adjacency[idx]
        elif trigger_variant == "coalition_valid_load":
            active = target_adjacency[idx] and bool(coalition_ready[idx]["sufficient"])
        else:
            active = False
        contributions.append(float(weight) if active else 0.0)
    return contributions


def _successful_load(*, weight, trigger_variant, players, sparse_list, food_removed):
    contributions = []
    any_sparse_positive = any(value > 0 for value in sparse_list)
    for idx, _player in enumerate(players):
        if trigger_variant == "positive_sparse_reward":
            active = sparse_list[idx] > 0
        elif trigger_variant == "food_removed":
            active = food_removed and any_sparse_positive
        else:
            active = False
        contributions.append(float(weight) if active else 0.0)
    return contributions


def _failed_load_penalty(*, weight, trigger_variant, players, action_list, sparse_list, target_adjacency):
    contributions = []
    for idx, _player in enumerate(players):
        did_load = action_list[idx] == 5
        if not did_load:
            contributions.append(0.0)
            continue
        failed = sparse_list[idx] <= 0
        if trigger_variant == "failed_load":
            active = failed
        elif trigger_variant == "failed_load_when_adjacent":
            active = failed and target_adjacency[idx]
        else:
            active = False
        contributions.append(float(weight) if active else 0.0)
    return contributions


def _assign_target_foods(raw_env, players):
    field = getattr(raw_env, "field", None)
    if field is None:
        return [None for _ in players]
    food_positions = _food_positions_from_field(field)
    assignments = []
    for player in players:
        if getattr(player, "position", None) is None or not food_positions:
            assignments.append(None)
            continue
        row, col = player.position
        assignments.append(
            min(
                food_positions,
                key=lambda pos: abs(row - pos[0]) + abs(col - pos[1]),
            )
        )
    return assignments


def _target_food_distances(_obs, players, target_assignments):
    distances = []
    for idx, player in enumerate(players):
        target = target_assignments[idx]
        if getattr(player, "position", None) is None or target is None:
            distances.append(None)
            continue
        row, col = player.position
        distances.append(abs(row - target[0]) + abs(col - target[1]))
    return distances


def _current_target_adjacency(players, target_assignments):
    adjacency = []
    for idx, player in enumerate(players):
        target = target_assignments[idx]
        if getattr(player, "position", None) is None or target is None:
            adjacency.append(False)
            continue
        row, col = player.position
        adjacency.append(abs(row - target[0]) + abs(col - target[1]) == 1)
    return adjacency


def _coalition_readiness(players, raw_env, target_assignments):
    field = getattr(raw_env, "field", None)
    readiness = []
    for idx, player in enumerate(players):
        target = target_assignments[idx]
        info = {"sufficient": False, "improves": False}
        if target is None or field is None:
            readiness.append(info)
            continue
        food_level = int(field[target[0], target[1]])
        if food_level <= 0:
            readiness.append(info)
            continue

        nearby_indices = [
            j
            for j, other in enumerate(players)
            if target_assignments[j] == target and getattr(other, "position", None) is not None
            and abs(other.position[0] - target[0]) + abs(other.position[1] - target[1]) <= 1
        ]
        coalition_level = sum(float(getattr(players[j], "level", 0)) for j in nearby_indices)
        info["sufficient"] = coalition_level >= food_level and len(nearby_indices) >= 1

        current_distance = abs(player.position[0] - target[0]) + abs(player.position[1] - target[1])
        info["improves"] = current_distance <= 2 and coalition_level > 0
        readiness.append(info)
    return readiness


def _food_removed(state_before, state_after, raw_env):
    field = getattr(raw_env, "field", None)
    if field is None:
        return False
    if state_before is None or state_after is None:
        return False
    return _sum_numeric(state_after) < _sum_numeric(state_before)


def _food_positions_from_field(field):
    positions = []
    rows = getattr(field, "shape", [0, 0])[0]
    cols = getattr(field, "shape", [0, 0])[1]
    for row in range(rows):
        for col in range(cols):
            if field[row, col] > 0:
                positions.append((row, col))
    return positions


def _target_agent_counts(target_assignments):
    counts = {}
    for target in target_assignments:
        if target is None:
            continue
        counts[target] = counts.get(target, 0) + 1
    return counts


def _actions_as_list(actions, num_agents):
    if isinstance(actions, list):
        return [int(value) for value in actions[:num_agents]]
    if isinstance(actions, tuple):
        return [int(value) for value in actions[:num_agents]]
    return [0 for _ in range(num_agents)]


def _reward_as_list(reward, num_agents):
    if isinstance(reward, list):
        return [float(value) for value in reward[:num_agents]]
    if isinstance(reward, tuple):
        return [float(value) for value in reward[:num_agents]]
    return [float(reward) for _ in range(num_agents)]


def _match_sparse_reward_shape(per_agent_dense, sparse_reward):
    if isinstance(sparse_reward, tuple):
        return tuple(float(value) for value in per_agent_dense)
    if isinstance(sparse_reward, list):
        return [float(value) for value in per_agent_dense]
    if not per_agent_dense:
        return 0.0
    return float(sum(per_agent_dense))


def _zero_like_list(reward):
    if isinstance(reward, tuple):
        return [0.0 for _ in reward]
    if isinstance(reward, list):
        return [0.0 for _ in reward]
    return [0.0]


def _add_scalar_to_dense(per_agent_dense, scalar):
    if not per_agent_dense:
        return
    for idx in range(len(per_agent_dense)):
        per_agent_dense[idx] += float(scalar)


def _sum_numeric(value):
    try:
        return float(value.sum())
    except Exception:
        if isinstance(value, (list, tuple)):
            return sum(_sum_numeric(item) for item in value)
        try:
            return float(value)
        except Exception:
            return 0.0
"""
